### ISSUE TITLE
Buster is suddenly not responsive over mac network

### ISSUE THREAD

**Issue by garyw7jzu** [mcdermj/buster#52]
I wonder if Apple's tightening of apps that exchange geo data is responsible for buster making the connection to the remote AMBEserver on an rpm 3 but not connecting to stations? Is there any issue related to this?

**Comment by boomertype** [comment]
Same issue, all the reflectors say - REFLECTOR DOES NOT EXIST
Buster is totally unusable, however you still still go Repeater direct, but doesn't allow you to be on reflectors.

**Comment by garyw7jzu** [comment]
This morning Buster has returned to its usual functioning.

Thanks Gary W7JZU

**Comment by mcdermj** [comment]
Buster gets its list of DPlus reflectors from the DPlus Authentication Service at opendstar.org. The site was refusing connection during my testing, so it appears as though there was an Internet outage at the site.

**Comment by garyw7jzu** [comment]
Thank you for the information

Gary W7JZU

**Comment by garyw7jzu** [comment]
FYI, for the past 4 days, the issue has reappeared with reflectors not existing

Thanks for your attention to this, Gary W7JZU

**Comment by mcdermj** [comment]
Again, this is not because of Buster.  This is because Robin Cutshaw's server at opendstar.org is refusing connections to the D-Plus authentication service.  Therefore Buster cannot authenticate to the D-Plus system or get any reflector information.  I can see if I can reach out to him, but until it's fixed, there is no Buster solution.

**Comment by garyw7jzu** [comment]
Annaliese,

Thank you for the response.

I do understand

73, Gary W7JZU

**Comment by mcdermj** [comment]
I just committed 79ec05 which will eventually be version 1.2.3 when it is deployed on the App Store.  After consulting with Robin about the architecture, it turns out there are multiple servers that should be tried in order, and there's a new name for them.  I have coded this into Buster which should make the authentication process more reliable.  I would expect Apple to approve 1.2.3 in the next couple of days and things should be more reliable for folks.

**Comment by garyw7jzu** [comment]
Well Done and thanks

Gary

**Comment by garyw7jzu** [comment]
Thanks, It is functioning now

73, Gary W7JZU

**Comment by garyw7jzu** [comment]
Hi McDerm folks,

My Buster app stopped functioning in the past few weeks. I suspect a recent MacOs upgrade but you know better than I.

Thanks for any help again

73, Gary W7JZU

**Comment by richark** [comment]
Gary,

Can you provide a few more details about how Buster is failing and on what
version of MacOS?  I've successfully used Buster on both Catalina and
Mojave. (latest version from the App store)

73,
Kenny, KU7M

**Comment by garyw7jzu** [comment]
Kenny,

After investigating the issue, I am concluding that it has to do with the Raspberry Pi and the Ambe card.

I will keep exploring issues related to that configuration.

Thanks for your response

73, Gary W7JZU

**Comment by richark** [comment]
No worries Gary, we have all be there. :-)

Good luck in your investigation, I hope you figure it out quickly.

73,
Kenny, KU7M
